//tealium universal tag - utag.12 ut4.0.202311162320, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag===undefined){utag={};}if(utag.ut===undefined){utag.ut={};}if(utag.ut.loader===undefined){u.loader=function(o){var a,b,c,l;a=document;if(o.type==="iframe"){b=a.createElement("iframe");b.setAttribute("height","1");b.setAttribute("width","1");b.setAttribute("style","display:none");b.setAttribute("src",o.src);}else if(o.type==="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";b.src=o.src;}if(o.id){b.id=o.id;}if(typeof o.cb==="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb();},false);}else{b.onreadystatechange=function(){if(this.readyState==="complete"||this.readyState==="loaded"){this.onreadystatechange=null;o.cb();}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l==="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b);}}};}else{u.loader=utag.ut.loader;}
u.ev={'view':1};u.initialized=false;u.map={};u.extend=[function(a,b){try{if(1){var dataLayer=b;var cobrowseEnv="",cobrowseGroupId="",countIterations=1;var truncated=dataLayer['cp.riblpid']?dataLayer['cp.riblpid']:"";var length="45";var appId=dataLayer&&(dataLayer.appId?dataLayer.appId:dataLayer.products&&dataLayer.products.length>0&&dataLayer.products[0].appId?dataLayer.products[0].appId:'');var visitorObj={visitorid:(truncated.substring(0,length))};try{cobrowseEnv=dataLayer["ut.env"]=="prod"?"production":"production";cobrowseGroupId=dataLayer["ut.env"]=="prod"?"19921":"20393";}catch(e){console.log("ERROR In setting Cobrowse env "+e)
}
if("undefined"==typeof GLANCE){var n=document,a=n.createElement("script"),c=n.head||n.getElementsByTagName("head")[0],r={id:"cobrowsescript",src:"https://www.glancecdn.net/cobrowse/CobrowseJS.ashx?group="+cobrowseGroupId+"&site="+cobrowseEnv,type:"text/javascript",async:"true","data-presence":"on","data-visitorid":visitorObj.visitorid,"data-groupid":cobrowseGroupId,"data-site":cobrowseEnv,charset:"UTF-8"};for(var i in r)a.setAttribute(i,r[i]);c.appendChild(a);var coBrowsebtn=function(pn){var trackObj={eVar35:pn,prop53:pn,linkTrackVars:'prop40,prop53,eVar35,eVar40,prop17,prop1,prop2,prop4,prop6,prop7,eVar8,eVar9,prop8,prop9,prop29,prop24,products,eVar90'};window.s?window.s.tl(window,'o',trackObj.prop53,trackObj):"";};window.GLANCE_COBROWSE={name:dataLayer['cp.s_ecid']?dataLayer['cp.s_ecid'].split("|")[1]:"",email:truncated,phone:appId};var script=document.querySelector('#cobrowsescript');script.addEventListener('load',function(){if("object"==typeof window.GLANCE){window.GLANCE.Cobrowse.Visitor.addEventListener('sessionstart',function(){coBrowsebtn('cobrowse standalone start unauthenticated');var termsLink=document.getElementById('glance_terms_link');termsLink&&termsLink.addEventListener('click',function(event){coBrowsebtn('cobrowse standalone view terms unauthenticated');event.target.removeEventListener(event.type,arguments.callee);});});window.GLANCE.Cobrowse.Visitor.addEventListener('sessionend',function(){coBrowsebtn('cobrowse standalone stop unauthenticated');});}else{console.log('### GLANCE oject not found');}});}
function docs_keyUp(event){if(event.ctrlKey&&event.key==="Enter"){GLANCE.Cobrowse.Visitor.startSession({sessionKey:"GLANCE_KEYTYPE_RANDOM"});}}
document.addEventListener('keyup',docs_keyUp,false);var cobrowseEleInterval=setInterval(function(){var jsElemet=Array.prototype.slice.call(document.querySelectorAll("#start-cobrowse-random-key,#cobrowseDesktop,#cobrowseMobile,#cobrowse,.cobrowseDesktop"));if(jsElemet&&jsElemet.length>0){clearInterval(cobrowseEleInterval);jsElemet.forEach(function(ele){if(ele.getAttribute("href")){ele.setAttribute("href","javascript:;");}
ele.addEventListener('click',function(e){GLANCE.Cobrowse.Visitor.startSession({sessionKey:"GLANCE_KEYTYPE_RANDOM"}),e.stopPropagation();});});}
if(countIterations++>=6){clearInterval(cobrowseEleInterval);}},1000);}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
}};utag.o[loader].loader.LOAD(id);})("12","usbank.dotcom-v2");}catch(error){utag.DB(error);}
