//tealium universal tag - utag.6 ut4.0.202311162320, Copyright 2023 Tealium.com Inc. All Rights Reserved.
try{(function(id,loader){var u={"id":id};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
var match=/ut\d\.(\d*)\..*/.exec(utag.cfg.v);if(utag.ut.loader===undefined||!match||parseInt(match[1])<35){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
if(utag.ut.typeOf===undefined){u.typeOf=function(e){return({}).toString.call(e).match(/\s([a-zA-Z]+)/)[1].toLowerCase();};}else{u.typeOf=utag.ut.typeOf;}
u.ev={"view":1};u.clearEmptyKeys=function(object){for(var key in object){if(object[key]===""||object[key]===undefined){delete object[key];}}
return object;};u.map={"adobeMarketingCloudVisitorId":"pdata.adobeid_new"};u.extend=[];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){utag.DB("send:6");utag.DB(b);var c,d,e,f;u.data={"base_url":"//di.rlcdn.com/","tag_id":"452709","pdata":{"timestamp":"","repeat_visitor":"","domain":"","device_type":"","traffic_source":"","referral_channel":"","referral_source":"","search_group":"","key_act_1":"","key_act_2":"","key_act_3":"","key_act_4":"","key_act_5":"","key_act_6":"","key_act_7":"","url_path":""}};utag.DB("send:6:EXTENSIONS");utag.DB(b);c=[];for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){if(e[f].indexOf("pdata.")===0){u.data.pdata[e[f].substr(6)]=b[d];}else{u.data[e[f]]=b[d];}}}}
utag.DB("send:6:MAPPINGS");utag.DB(u.data);if(!u.data.tag_id){utag.DB(u.id+": Tag not fired: Required attribute not populated");return;}
u.data.pdata.timestamp=u.data.timestamp;u.data.pdata.repeatvisitor=u.data.repeat_visitor;u.data.pdata.domain=u.data.domain;u.data.pdata.devicetype=u.data.device_type;u.data.pdata.trafficsource=u.data.traffic_source;u.data.pdata.refferalchannel=u.data.referral_channel;u.data.pdata.refferalsource=u.data.referral_source;u.data.pdata.searchgroup=u.data.search_group;u.data.pdata.keyact1=u.data.key_act_1;u.data.pdata.keyact2=u.data.key_act_2;u.data.pdata.keyact3=u.data.key_act_3;u.data.pdata.keyact4=u.data.key_act_4;u.data.pdata.keyact5=u.data.key_act_5;u.data.pdata.keyact6=u.data.key_act_6;u.data.pdata.keyact7=u.data.key_act_7;u.data.pdata.urlpath=u.data.url_path;u.data.pdata=u.clearEmptyKeys(u.data.pdata);var paramstr="";for(key in u.data.pdata){paramstr+=(key+"="+u.data.pdata[key]+",");}
paramstr=paramstr.slice(0,-1);paramstr=encodeURIComponent(paramstr);if(paramstr){paramstr='?pdata='+paramstr;}
u.data.base_url=u.data.base_url+u.data.tag_id+".html"+paramstr;u.loader({"type":"iframe","src":u.data.base_url,"cb":null,"loc":"body","id":"utag_6","attrs":{}});utag.DB("send:6:COMPLETE");}};utag.o[loader].loader.LOAD(id);}("6","usbank.dotcom-v2"));}catch(error){utag.DB(error);}
